test:
  adapter: jdbcsqlite3
  encoding: utf8
  database: build/centerservice_test.sqlite3

development:
  adapter: postgresql
  encoding: utf8
  username: centerui
  password: centerui
  database: centerui_development
